#!/usr/bin/env python3
import os
import sys

msg = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Update XuanJi-OS"

os.system("./version.sh")
os.system("git add .")
os.system(f'git commit -m "{msg}"')
os.system("git push")
